#name: matrix-strategy-example
#
#on:
#  workflow_dispatch:
#
#  push:
#    branches:
#      - main
#
#  pull_request:
#    branches:
#      - main
#
#
#jobs:
#  matrix-example:
#    runs-on: ubuntu
#    strategy:
#      matrix:
#        node-version: [ 16,18,20 ]
#
#    steps:
#      - uses: actions/checkout@v4
#      - run: node -v
#
