name: My First Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@latest_version

      - name: Use Node.js
        uses: actions/setup-node@latest_version
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm ci
